# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\">\n\rSignUpRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"5\n\x0c\x41uthResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\" \n\x0fValidateRequest\x12\r\n\x05token\x18\x01 \x01(\t\"G\n\x10ValidateResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0b\x63laims_json\x18\x03 \x01(\t2\xaa\x01\n\x04\x41uth\x12\x31\n\x06SignUp\x12\x13.auth.SignUpRequest\x1a\x12.auth.AuthResponse\x12/\n\x05Login\x12\x12.auth.LoginRequest\x1a\x12.auth.AuthResponse\x12>\n\rValidateToken\x12\x15.auth.ValidateRequest\x1a\x16.auth.ValidateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNUPREQUEST']._serialized_start=20
  _globals['_SIGNUPREQUEST']._serialized_end=82
  _globals['_LOGINREQUEST']._serialized_start=84
  _globals['_LOGINREQUEST']._serialized_end=131
  _globals['_AUTHRESPONSE']._serialized_start=133
  _globals['_AUTHRESPONSE']._serialized_end=186
  _globals['_VALIDATEREQUEST']._serialized_start=188
  _globals['_VALIDATEREQUEST']._serialized_end=220
  _globals['_VALIDATERESPONSE']._serialized_start=222
  _globals['_VALIDATERESPONSE']._serialized_end=293
  _globals['_AUTH']._serialized_start=296
  _globals['_AUTH']._serialized_end=466
# @@protoc_insertion_point(module_scope)
